import SignInForm from '@/components/auth/Login'
import { Metadata } from 'next'
import { Suspense } from 'react'

const page = () => {
  return (
    <div>
      <Suspense fallback={
        <div className="flex items-center justify-center min-h-[400px]">
          <div className="animate-spin rounded-full h-8 w-8 border-t-2 border-b-2 border-[#1a3c6e]"></div>
        </div>
      }>
        <SignInForm />
      </Suspense>
    </div>
  )
}

export default page

export const metadata: Metadata = {
  title: "Login | Westfert Fertilisers",
  description: "Generated by create next app",
};