export enum FEATURES {
  GARDEN = "GARDEN",
  PARKING = "PARKING",
  NEW_BUILD = "NEW_BUILD",
  CHAIN_FREE = "CHAIN_FEE",
  SWIMMING_POOL = "SWIMMING_POOL",
  GYM = "GYM",
  CONCIERGE = "CONCIERGE",
  BALCONY = "BALCONY",
  TERRACE = "TERRACE",
  LIFT = "LIFT",
  FITTED_KITCHEN = "FITTED_KITCHEN",
  UNDER_FLOOR_HEATING = "UNDER_FLOOR_HEATING",
  SOLAR_PANELS = "SOLAR_PANELS",
  OFF_STREET_PARKING = "OFF_STREET_PARKING",
  DRIVEWAY = "DRIVEWAY",
  ALARM_SYSTEM = "ALARM_SYSTEM",
}

export enum PROPERTY_TYPE {
  DETACHED = "DETACHED",
  SEMI = "SEMI",
  TERRACED = "TERRACED",
  BANGLOW = "BANGLOW",
  FLAT = "FLAT",
  PARK_HOME = "PARK_HOME",
}
export enum TENURE {
  FREEHOLD = "FREEHOLD",
  LEASEHOLD = "LEASEHOLD",
  SHARE_OF_FREEHOLD = "SHARE_OF_FREEHOLD",
}
export const COUNCIL_TAX_BANDS = ["A", "B", "C", "D", "E", "F", "G", "H"];
export const EPC_RATINGS = ["A", "B", "C", "D", "E", "F", "G"];
